---
host: localhost
logsdir: logs
loglevel: info
datadir: data
keepdata: no # or yes
plugindirs:
  - plugins
zabbix:
  host: zabbix.example.com
  port: 10051
  sender: /usr/bin/zabbix_sender
plugins:
  - name: memory
  - name: cpu
  - name: network
    args: [ eth0 ]
  - name: disk
    args: [ sda1, / ]
  - name: network
    args: [ eth1 ]
